### ISSUE TITLE
Pixelated icons

### ISSUE THREAD

**Issue by vivadavid** [YACReader/yacreader#314]
Hi, Luis,

I've just updated to version 9.9.0 and I've noticed that the icons look pixelated.

Thanks!

![ - 000881](https://user-images.githubusercontent.com/9334287/188283773-589882b6-3d99-4621-9159-286e4db77ffc.png)

**Comment by luisangelsm** [comment]
Yeah, it is a limitation because of the state Qt is in (the toolkit I use to develop YACReader). There is a bug preventing me from migrating all the icons to SVG (https://bugreports.qt.io/browse/QTBUG-96553). 9.9.0 adds support for HDPI screens, but current icons won't scale. So if your screen scale ratio is bigger than 100% there will be some pixelation.

If this becomes too annoying I will try to do something about it.

**Comment by vivadavid** [comment]
Hi, Luis,

Thanks for your quick reply. My screen is, in fact, set to 125%, but the pixelation is not a big deal, so don't bother too much!

**Comment by vivadavid** [comment]
Hi, @luisangelsm,

Thank you for fixing this on version 9.10!
