### ISSUE TITLE
Migrate from Qt Script to QJson

### ISSUE THREAD

**Issue by selmf** [YACReader/yacreader#51]
We're still using the outdated and deprecated Qt Script for our ComicVine scraper. This is no longer shipped in default Qt installations, so it makes the build process slightly more complicated and could lead to problems in the future. It is also a dependency we could get rid of.

We should migrate the scraper code to QJSEngine.

**Comment by selmf** [comment]
As we only use the script engine to parse json data, migrating to QJson seems to be the saner choice.

**Comment by jeremydouglass** [comment]
If this is being refactored anyway, I wonder whether the scraper parsing logic could be a module / plugin / script rather than compiled into the app itself. It would be really nice for me to be able to swap out the comicvine scraper with a different data source.

**Comment by selmf** [comment]
Not at this point. The goal is to keep it working and maybe extend it a bit.

**Comment by luisangelsm** [comment]
@jeremydouglass what other source do you have in mind?

**Comment by selmf** [comment]
Just to be clear, we can only support sources who's terms of service allow it.

**Comment by jeremydouglass** [comment]
> we can only support sources who's terms of service allow it.

Of course. My suggestion is not for you to write the code to support any new sources -- just to expose the metadata collection mechanism in a way that it could be reconfigured / replaced, whether importing, side-loading metadata from other sources, et cetera.

> @jeremydouglass what other source do you have in mind?

For example, if the JSON import code was pluggable rather than hardcoded in the app then someone could run a JSON frontend on the Grand Comics Database, which provides dumps licensed under Creative Commons Attribution. Or  use their Marvel API developer keys. Or bring in data from future metadata formats -- if [Anansi](https://github.com/anansi-project/rfcs) is ever developed, for example. Or they could could write their own JSON API endpoint -- in my case I run a university research project that is collecting custom metadata on comics, and I'm thinking about making a JSON API end point to that data. Et cetera. None of this would need to be supported by you -- it is just something that someone could do if you allowed them to access the part of the code that retrieves json and passes it in when you press the button. Your parsing in-app logic could stay Comic Vine centric, and it would be up to the person extending the fetcher to match the json you are expecting.

**Comment by luisangelsm** [comment]
The existing json parsing is tied to the ComicVine API because it can't be generic, all the data ends in the data base, so you need to convert any information source data into the DB format and the access to the database has its own API. So integrating additional sources is just a matter of creating new implementations for those sources, from a UI/UX perspective I am not sure if the current dialog makes sense for other sources.

Basically what you want is to be able to populate a `ComicDB` with new information and update it in the DB. How you get the data is up to you.

I don't think I am going to have time to add an API to support modules/plugins, and I am not sure if I want to do it, because once plugins are installed giving support is going to be a pita. But I am perfectly fine accepting PRs that expand the way of importing metadata into YACReaderLibrary if it will be helpful for the users. I'll help as much as possible. e.g. we need to add support for xml metada (which has a legacy format), adding it + adding support for json using the same key names could by a way of supporting any external json source (some transformations to the json would be needed) and I think it could work for your case.

For your specific use case, which is something it won't be public, you have a couple of options with the existing source code: 1) maintain a fork where you integrate your end point into YACReaderLibrary, or 2) try to modify the DB directly, you can create a basic UI for browsing and updating comics metadata by inserting it in the DB, then that info will be available in YACReaderLibrary.

**Comment by jeremydouglass** [comment]
> from a UI/UX perspective I am not sure if the current dialog makes sense for other sources.

That is a good point.

> expand the way of importing metadata [...] try to modify the DB directly

This sounds sensible. Where is the db, by the way? I vaguely remembered it as a sqlite in ~/Libraries/Applications Support/YACReader -- but apparently not; I can't seem to find it.

**Comment by selmf** [comment]
Migration is done and QtScript will no longer be a dependency as of 9.8
