### ISSUE TITLE
Grid View broke with the latest qt5 update

### ISSUE THREAD

**Issue by wallace11** [YACReader/yacreader#71]
This is basically a requested issue [from the forums](https://www.yacreader.com/forum/support-linux/1362-grid-view-broke-with-newest-qt5-update).

The error is:
```
ERROR 2019-07-03T22:38:43.681 (qrc:/qml/GridComicsView.qml:439:9: Cannot assign object of type "Component" to property of type "QQuickItem*" as the former is neither the same as the latter nor a sub-class of it.)
```

**Comment by selmf** [comment]
Thanks for taking the time to open the issue here. The issue is caused by this [change](https://codereview.qt-project.org/c/qt/qtdeclarative/+/249661) introduced in Qt 5.13, which makes an assignment in our qml code illegal.
If you use YACReader on Archlinux or a derivate I've already pushed a new package to the AUR which has a patch for this. We probably won't do a minor release for this, but if @luisangelsm is ok with it I can add the patch to the master branch for easy picking. Otherwise it'll go to the development branch only.

**Comment by wallace11** [comment]
Just finished recompiling with your patch.
It indeed fixes the issue. However, the grid is now misaligned, which is not a huge deal but should probably be fixed before the release ;)

**Comment by selmf** [comment]
Yes, I noticed something similar, but wasn't sure if this was caused by the patch. So thanks for confirming it. My 'fix' is basically a quick and dirty adaption of a patch upstream Qt used for a similar error, so I didn't dig too deep. I'll keep this issue open as a reminder.

**Comment by luisangelsm** [comment]
@wallace11 can you confirm if both the error and aliment problem are gone in `develop`?

**Comment by wallace11** [comment]
> @wallace11 can you confirm if both the error and aliment problem are gone in `develop`?

I'm using the [patch](https://aur.archlinux.org/cgit/aur.git/tree/qml_error.patch?h=yacreader) submitted to AUR by @selmf. Is that the same one that's on `develop`? If so it's working just fine :)

**Comment by luisangelsm** [comment]
The misaligment problem should be gone now...

**Comment by selmf** [comment]
@wallace11 there is a subtle difference between the two patches. I unintentionally removed a line when fixing the problem and that caused the misplacement. @luisangelsm fixed that. I still need to update the patch on the AUR though.

@luisangelsm, I think we can close this bug now.

**Comment by wallace11** [comment]
Just finished recompiling the dev branch (really wish qt was less heavy).
Looks good here so I close the issue.
Thanks!
